FROM bitnami/spark:3.4.1

USER root

RUN mkdir -p /home/spark/working_dir

# Update pip
RUN python -m pip install --upgrade pip

# # Copy requirements.txt to the docker image
# COPY ./requirements.txt /

# # Install the dependencies
# RUN pip install -r /requirements.txt

USER 1001